In [45]:
#Importing Libraries

In [46]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [47]:
#Importing Dataset

In [48]:
file=pd.read_csv(r'C:\Users\Priyansh\Downloads\Netflix_stock_data.csv')

In [49]:
# Understanding the Data

In [50]:
file.head()

Date     Close      High       Low      Open     Volume
0  2002-05-23  1.196429  1.242857  1.145714  1.156429  104790000
1  2002-05-24  1.210000  1.225000  1.197143  1.214286   11104800
2  2002-05-28  1.157143  1.232143  1.157143  1.213571    6609400
3  2002-05-29  1.103571  1.164286  1.085714  1.164286    6757800
4  2002-05-30  1.071429  1.107857  1.071429  1.107857   10154200

In [51]:
file.tail()

Date        Close         High          Low         Open   Volume
5805  2025-06-18  1222.290039  1242.000000  1220.500000  1229.989990  2281000
5806  2025-06-20  1231.410034  1248.500000  1224.349976  1234.449951  5348200
5807  2025-06-23  1253.540039  1254.839966  1215.010010  1238.030029  2667300
5808  2025-06-24  1279.109985  1282.569946  1255.000000  1260.550049  2663300
5809  2025-06-25  1275.250000  1298.000000  1273.810059  1286.839966  2144100

In [52]:
file.isnull().sum()

Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [53]:
file.nunique()

Date      5810
Close     5326
High      5234
Low       5221
Open      5233
Volume    5640
dtype: int64

In [54]:
# Dropping irrelevant Columns

In [55]:
data=file.drop(["Date"],axis=1)

In [56]:
x=data.iloc[:,1:].values #independent variables
y=data.iloc[:,1].values #dependent variables
print(x)
print()
print(y)

[[1.24285698e+00 1.14571404e+00 1.15642905e+00 1.04790000e+08]
 [1.22500002e+00 1.19714296e+00 1.21428597e+00 1.11048000e+07]
 [1.23214304e+00 1.15714300e+00 1.21357095e+00 6.60940000e+06]
 ...
 [1.25483997e+03 1.21501001e+03 1.23803003e+03 2.66730000e+06]
 [1.28256995e+03 1.25500000e+03 1.26055005e+03 2.66330000e+06]
 [1.29800000e+03 1.27381006e+03 1.28683997e+03 2.14410000e+06]]

[1.24285698e+00 1.22500002e+00 1.23214304e+00 ... 1.25483997e+03
 1.28256995e+03 1.29800000e+03]


In [57]:
#Spliting the Datset into Training set and Test set

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [60]:
print(x_train)

[[1.32700005e+01 1.25357141e+01 1.30671434e+01 8.44837000e+07]
 [1.01440002e+02 9.78199997e+01 9.83399963e+01 1.24322000e+07]
 [8.94999981e+00 8.32142925e+00 8.34142876e+00 7.60648000e+07]
 ...
 [3.23399994e+02 3.18140015e+02 3.23170013e+02 5.64290000e+06]
 [1.66285706e+00 1.55357099e+00 1.63499999e+00 1.10712000e+07]
 [3.12709991e+02 3.02549988e+02 3.09200012e+02 1.46269000e+07]]


In [61]:
print(x_test)

[[2.68899994e+01 2.58999996e+01 2.66885719e+01 3.82312000e+07]
 [1.73857105e+00 1.62571394e+00 1.62571394e+00 2.42851000e+07]
 [5.36428595e+00 5.00285721e+00 5.15714312e+00 5.70612000e+07]
 ...
 [8.35999966e+00 7.81571388e+00 8.18714333e+00 5.75470000e+06]
 [5.73428583e+00 5.58857107e+00 5.61571407e+00 1.20841000e+07]
 [5.21489990e+02 5.05549988e+02 5.17900024e+02 4.22900000e+06]]


In [62]:
print(y_train)

[ 13.27000046 101.44000244   8.94999981 ... 323.3999939    1.66285706
 312.70999146]


In [63]:
print(y_test)

[ 26.88999939   1.73857105   5.36428595 ...   8.35999966   5.73428583
 521.48999023]


In [64]:
# Feature Scaling

In [65]:
from sklearn.preprocessing import StandardScaler

In [66]:
sc=StandardScaler()

In [67]:
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [68]:
print(x_train)

[[-0.67738219 -0.6768369  -0.67656626  3.70868218]
 [-0.30762142 -0.30940599 -0.31402882 -0.14521901]
 [-0.69549909 -0.69499333 -0.69665763  3.25837082]
 ...
 [ 0.62321783  0.63980034  0.64183574 -0.50836609]
 [-0.72605936 -0.72415135 -0.72517    -0.21801638]
 [ 0.57838689  0.57263372  0.58244229 -0.02782858]]


In [69]:
print(x_test)

[[-0.62850068 -0.62820506 -0.62754821  1.36332269]
 [-0.7286557  -0.72749276 -0.72874502  0.54165229]
 [-0.71421781 -0.71367943 -0.7144861   2.47274063]
 ...
 [-0.70228864 -0.70217416 -0.7022518  -0.55011395]
 [-0.71274444 -0.71128371 -0.71263452 -0.17720105]
 [ 1.3410364   1.33367938  1.35582627 -0.64000449]]
